arduino-cli lib install "Sensirion Core"
arduino-cli lib install "Sensirion I2C SCD4x"
arduino-cli lib install "Sensirion I2C SHT4x"
arduino-cli lib install "DHT sensor library"
arduino-cli lib install "Adafruit Unified Sensor"