// Keyed by the exact summary strings produced by the server for Open-Meteo's WMO weather codes.
export const WEATHER_ICONS: Record<string, string> = {
  'Clear sky': '☀️',
  'Mainly clear': '🌤️',
  'Partly cloudy': '⛅',
  Overcast: '☁️',
  Fog: '🌫️',
  'Depositing rime fog': '🌫️',
  'Light drizzle': '🌦️',
  'Moderate drizzle': '🌦️',
  'Dense drizzle': '🌧️',
  'Light freezing drizzle': '🌨️',
  'Dense freezing drizzle': '🌨️',
  'Slight rain': '🌦️',
  'Moderate rain': '🌧️',
  'Heavy rain': '🌧️',
  'Light freezing rain': '🌨️',
  'Heavy freezing rain': '🌨️',
  'Slight snow fall': '🌨️',
  'Moderate snow fall': '❄️',
  'Heavy snow fall': '❄️',
  'Snow grains': '🌨️',
  'Slight rain showers': '🌦️',
  'Moderate rain showers': '🌧️',
  'Violent rain showers': '⛈️',
  'Slight snow showers': '🌨️',
  'Heavy snow showers': '❄️',
  Thunderstorm: '⛈️',
  'Thunderstorm with slight hail': '⛈️',
  'Thunderstorm with heavy hail': '⛈️',
  Unknown: '❓',
};
