// <auto-generated />
using System;
using Kelvin.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kelvin.Server.Data.Migrations
{
    [DbContext(typeof(KelvinContext))]
    [Migration("20260803010829_MovingForecastLockouts")]
    partial class MovingForecastLockouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Kelvin.Server.Models.ControlStateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float?>("CO2LevelPpm")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("EnvironmentTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<float?>("ForecastTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<float?>("HumidityPercentage")
                        .HasColumnType("REAL");

                    b.Property<float?>("HysteresisC")
                        .HasColumnType("REAL");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousState")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PreviousStateDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SetPointId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("TargetTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "CreatedAt");

                    b.ToTable("ControlStateChanges");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Gateway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ControlPin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoolingPin")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FanPin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeatingPin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinimumOffDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumOnDurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Gateways");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Preferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeFormat")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<float>("TargetTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ThermostatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThermostatId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBattery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCO2Sensor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHumiditySensor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MacAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Kelvin.Server.Models.SensorPacket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("BatteryLevelPercentage")
                        .HasColumnType("REAL");

                    b.Property<ushort>("CO2LevelPpm")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<float>("HumidityPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SensorId")
                        .HasColumnType("TEXT");

                    b.Property<float>("TemperatureC")
                        .HasColumnType("REAL");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorPackets");
                });

            modelBuilder.Entity("Kelvin.Server.Models.SetPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TargetTemperatureC")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ThermostatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThermostatId");

                    b.ToTable("SetPoints");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Thermostat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float?>("CoolingLockoutC")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FanEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("HeatingLockoutC")
                        .HasColumnType("REAL");

                    b.Property<float>("HysteresisC")
                        .HasColumnType("REAL");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Thermostats");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Schedule", b =>
                {
                    b.HasOne("Kelvin.Server.Models.Thermostat", "Thermostat")
                        .WithMany("Schedules")
                        .HasForeignKey("ThermostatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thermostat");
                });

            modelBuilder.Entity("Kelvin.Server.Models.SensorPacket", b =>
                {
                    b.HasOne("Kelvin.Server.Models.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Kelvin.Server.Models.SetPoint", b =>
                {
                    b.HasOne("Kelvin.Server.Models.Thermostat", "Thermostat")
                        .WithMany("SetPoints")
                        .HasForeignKey("ThermostatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thermostat");
                });

            modelBuilder.Entity("Kelvin.Server.Models.Thermostat", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("SetPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
